spring:
  application:
    name: mtchat
  profiles:
    active: dev
  cache:
    type: caffeine
  datasource:
    url: jdbc:mysql://${mtchat.mysql.host}:${mtchat.mysql.port}/${mtchat.mysql.database}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mtchat.mysql.username}
    password: ${mtchat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${mtchat.redis.host}
    # Redis服务器端口号
    port: ${mtchat.redis.port}
    # 使用的数据库索引，默认是0
    database: ${mtchat.redis.database}
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${mtchat.redis.password}
  jackson:
    serialization:
      # 在交互时自动把时间转为时间戳
      write-dates-as-timestamps: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


rocketmq:
  name-server: ${rocketmq.name-server}
  # 默认的消息组
  producer:
    group: chatGroup
    send-message-timeout: 3000 # 发送消息超时时间，单位：毫秒。默认为 3000 。
    compress-message-body-threshold: 4096 # 消息压缩阀值，当消息体的大小超过该阀值后，进行消息压缩。默认为 4 * 1024B
    max-message-size: 4194304 # 消息体的最大允许大小。。默认为 4 * 1024 * 1024B
    retry-times-when-send-failed: 2 # 同步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-async-failed: 2 # 异步发送消息时，失败重试次数。默认为 2 次。
    retry-next-server: false # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false
    access-key: ${rocketmq.access-key} # Access Key ，可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/acl/user_guide.md 文档
    secret-key: ${rocketmq.secret-key} # Secret Key
    enable-msg-trace: true # 是否开启消息轨迹功能。默认为 true 开启。可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/msg_trace/user_guide.md 文档
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC # 自定义消息轨迹的 Topic 。默认为 RMQ_SYS_TRACE_TOPIC 。
  # Consumer 配置项
  consumer:
    access-key: ${rocketmq.access-key} # Access Key ，可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/acl/user_guide.md 文档
    secret-key: ${rocketmq.secret-key} # Secret Key
    listeners: # 配置某个消费分组，是否监听指定 Topic 。结构为 Map<消费者分组, <Topic, Boolean>> 。默认情况下，不配置表示监听。
      erbadagang-consumer-group:
        topic1: false # 关闭 test-consumer-group 对 topic1 的监听消费


mtchat:
  jwt:
    secret-key: ${mtchat.jwt.secret-key}
  thread-pool:
    common:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 500
      thread-name-prefix: mtchat-executor-
    websocket-push:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 500
      thread-name-prefix: websocket-push-executor-

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


wx:
  mp:
    configs:
      - app-id: ${mtchat.wx.app-id}
        aes-key: ${mtchat.wx.aes-key}
        secret: ${mtchat.wx.secret}
        token: ${mtchat.wx.token}
    callback: ${mtchat.wx.callback}

oss:
  type: ${oss-dev.type}
  enabled: ${oss-dev.enabled}
  endpoint: ${oss-dev.endpoint}
  access-key: ${oss-dev.access-key}
  secret-key: ${oss-dev.secret-key}
  bucket-name: ${oss-dev.bucketName}

sensitive-word:
  type: ac
